Fix StaleElementException in setValue when input has gone away
minkphp/MinkSelenium2Driver pull request #336
Opened 2021-08-24 19:28 UTC by Chekote

## Problem
Some websites using a SPA approach have implemented behavior where when a correct value is entered into an input, it is immediately recognized and the SPA updates instantly, causing the input to be detached from the DOM.

When this happens, the input is set correctly via the `$element->postValue()` call from `setValue()`, but when it then proceeds to call `$this->executeJsOnElement()`, a StaleElementException is thrown because the input is no longer attached to the DOM.

## Fix
Catch and swallow the exception.

## Rationale
It is not possible to execute JS on an element that is detached from the DOM, so it is impossible to attempt to unfocus it at this point (at least by executing JS on it).

The goal is to unfocus the element, which if it is detached from the DOM, it is clearly unfocused at this point.

2021-08-24 21:04 UTC, Chekote commented
Seems like your Travis CI is broken? It didn't run on the PR.

2021-08-24 21:14 UTC, Chekote commented
@aik099 sorry to bug you, but I wanted to make sure you saw this PR since your CI seems to be broken.

2021-09-04 05:58 UTC, aik099 requested changes

2021-09-04 05:58 UTC, aik099 commented on src/Selenium2Driver.php
> +        // no longer attached to the page document.
Please replace with:

```php
// Cover case, when an element was removed from DOM after its value was
// changed (e.g. by a JavaScript of a SPA) and therefore can't be focused.
```

---

People always can use git annotate to locate associated PR, which explains all in much greater detail.

2021-09-04 05:58 UTC, aik099 commented on src/Selenium2Driver.php
> +            // and therefore is no longer focused (nor can it be blurred).
Please replace with:
```php
// Do nothing because an element was already removed and therefore
// blurring is not needed.
```

2021-09-04 06:01 UTC, aik099 commented
Nice bug report by the way. Very detailed. Thank you @Chekote .

2021-09-05 16:14 UTC, aik099 approved these changes

2021-09-05 16:14 UTC, merged

2021-09-05 16:15 UTC, aik099 commented
Merging, thanks @Chekote .